# Generated by Django 2.2.9 on 2020-01-17 13:16

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagepartner_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Ondertitle'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Naam'),
        ),
    ]
