# Generated by Django 2.2.9 on 2020-01-17 13:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0004_auto_20200117_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='data_text',
            field=models.CharField(default='Check dates', max_length=32, verbose_name='Data tekst'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='download_text',
            field=models.CharField(default='Download DBS Brochure', max_length=32, verbose_name='Download tekst'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sessions',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Sessies'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sessions_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Afbeelding'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sessions_info',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Wat?'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Afbeelding'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_info',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Info'),
        ),
    ]
