# Generated by Django 2.2.9 on 2020-01-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0005_auto_20200117_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, verbose_name='plaats')),
                ('postal_code', models.CharField(max_length=8, verbose_name='postcode')),
                ('street', models.CharField(max_length=40, verbose_name='straat')),
                ('number', models.CharField(max_length=8, verbose_name='huisnummer')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addressen',
                'ordering': ['city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Address')),
                ('name', models.CharField(max_length=64, verbose_name='location name')),
            ],
            options={
                'verbose_name': 'locatie',
                'verbose_name_plural': 'locaties',
                'ordering': ['name'],
            },
            bases=('home.address',),
        ),
        migrations.CreateModel(
            name='BDSSelectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('error_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='logo')),
                ('logo_white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='logo (wit)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Location')),
            ],
            options={
                'verbose_name': 'Health House data',
            },
        ),
    ]
