# Generated by Django 2.2.9 on 2020-01-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_address_bdsselectsettings_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdsselectsettings',
            options={'verbose_name': 'DBS Select data'},
        ),
    ]
