# Generated by Django 2.2.9 on 2020-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200117_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='movie_link',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='movie_title',
            field=models.CharField(max_length=64, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Naam'),
        ),
    ]
