# Generated by Django 2.2.9 on 2020-01-17 14:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0008_auto_20200117_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naam')),
                ('info', models.CharField(max_length=64, verbose_name='Info')),
                ('age', models.IntegerField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Persoon',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='HomePageTestimonial',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Person')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('testimonial', wagtail.core.fields.RichTextField(null=True, verbose_name='getuigenis')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
            bases=('home.person', models.Model),
        ),
    ]
