# Generated by Django 2.2.9 on 2020-01-21 19:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0009_homepagetestimonial_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Achtergrond'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Ondertitel'),
        ),
    ]
