# Generated by Django 2.2.9 on 2020-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200121_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonials_subtitle',
            field=models.CharField(default='from people participating in a DBS session', max_length=64, verbose_name='Ondertitel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(default='Testimonials', max_length=32, verbose_name='Getuigenissen'),
        ),
    ]
