# Generated by Django 2.2.9 on 2020-01-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0011_auto_20200122_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='funded',
            field=models.CharField(default='Project funded by', max_length=32, verbose_name='Funded by'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='funded_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Afbeelding'),
        ),
    ]
