# Generated by Django 2.2.9 on 2020-01-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0013_homepage_partners_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='data_link',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Bestand'),
        ),
    ]
