# Generated by Django 2.2.9 on 2020-01-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0014_auto_20200122_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdsselectsettings',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='favicon'),
        ),
    ]
