# Generated by Django 2.2.9 on 2020-03-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepagevideo_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['video'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
