# Generated by Django 2.2.9 on 2020-03-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200319_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='videos_discription',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Ondertitel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='videos_title',
            field=models.CharField(default='More videos', max_length=32, verbose_name='Videos'),
        ),
    ]
