# Generated by Django 2.2.9 on 2020-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200319_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.URLField(null=True, verbose_name='Video link'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='Titel'),
        ),
    ]
