# Generated by Django 3.2.6 on 2021-08-23 19:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0019_auto_20200320_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('block_1_title', models.CharField(max_length=54, verbose_name='deel 1 tite')),
                ('block_1_description', models.TextField(verbose_name='deel 1 beschrijving')),
                ('block_2_title', models.CharField(max_length=54, verbose_name='deel 2 titel')),
                ('block_2_description', models.TextField(verbose_name='deel 2 beschrijving')),
                ('block_3_title', models.CharField(max_length=54, verbose_name='deel 3 titel')),
                ('block_3_description', models.TextField(verbose_name='deel 3 beschrijving')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SessionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Inhoud getuigenis')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.person')),
            ],
            options={
                'verbose_name': 'Getuigenis',
                'verbose_name_plural': 'Getuigenissen',
            },
        ),
        migrations.CreateModel(
            name='SessionsPageTestimonial',
            fields=[
                ('testimonial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.testimonial')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.sessionspage')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.testimonial')),
            ],
            options={
                'ordering': ['sort_order'],
            },
            bases=('home.testimonial', models.Model),
        ),
    ]
