# Generated by Django 3.2.6 on 2021-08-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0020_auto_20210828_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='titel')),
                ('content', models.CharField(max_length=512, verbose_name='korte inhoud')),
                ('url', models.URLField(verbose_name='link')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'pers artikel',
                'verbose_name_plural': 'pers artikels',
            },
        ),
    ]
