# Generated by Django 3.2.6 on 2021-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='link',
            field=models.URLField(max_length=64, verbose_name='URL'),
        ),
    ]
