# Generated by Django 3.2.6 on 2021-08-28 11:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_session_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsPageSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.session')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='home.sessionspage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.session', verbose_name='sessie')),
            ],
            options={
                'ordering': ['sort_order'],
            },
            bases=('home.session', models.Model),
        ),
    ]
