# Generated by Django 3.2.6 on 2021-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text',
            field=models.CharField(blank=True, max_length=160, verbose_name='success message'),
        ),
    ]
