# Generated by Django 3.2.6 on 2021-09-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0025_contactpage_directions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='block_1_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Afbeelding'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='block_2_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Afbeelding'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='block_3_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Afbeelding'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='video'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_1_description',
            field=models.TextField(verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_1_title',
            field=models.CharField(max_length=54, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_2_description',
            field=models.TextField(verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_2_title',
            field=models.CharField(max_length=54, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_3_description',
            field=models.TextField(verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_3_title',
            field=models.CharField(max_length=54, verbose_name='titel'),
        ),
    ]
