# Generated by Django 3.2.6 on 2021-09-04 11:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210904_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=64)), ('content', wagtail.core.blocks.TextBlock(max_length=512)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock, required=False))]))], null=True),
        ),
    ]
