# Generated by Django 3.2.6 on 2021-09-04 19:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0027_aboutpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='block_1_description',
            field=models.TextField(blank=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Afbeelding'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_1_title',
            field=models.CharField(blank=True, max_length=54, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_2_description',
            field=models.TextField(blank=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Afbeelding'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_2_title',
            field=models.CharField(blank=True, max_length=54, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_3_description',
            field=models.TextField(blank=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Afbeelding'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='block_3_title',
            field=models.CharField(blank=True, max_length=54, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='titel', max_length=64)), ('content', wagtail.core.blocks.TextBlock(label='tekst', max_length=512)), ('image', wagtail.images.blocks.ImageChooserBlock(label='afbeelding', required=False)), ('gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), label='foto gallerij', required=False))]))], null=True),
        ),
    ]
