# Generated by Django 3.2.6 on 2021-09-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210904_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='send_button',
            field=models.CharField(default='Verzenden', max_length=28, verbose_name='verzend text'),
        ),
    ]
