# Generated by Django 3.2.6 on 2021-09-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0029_contactpage_send_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naam')),
                ('title', models.CharField(max_length=128, verbose_name='Titel')),
                ('text', models.CharField(max_length=300, verbose_name='Info')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Teamlid',
                'verbose_name_plural': 'Teamleden',
            },
        ),
    ]
