# Generated by Django 3.2.6 on 2021-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_mediapage_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapage',
            name='media_title',
            field=models.CharField(default='Media', max_length=64, verbose_name='titel media'),
        ),
        migrations.AddField(
            model_name='mediapage',
            name='press_title',
            field=models.CharField(default='Press', max_length=64, verbose_name='titel pers'),
        ),
    ]
