# Generated by Django 3.2.6 on 2021-09-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210922_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionsPageTestimonial',
        ),
    ]
