# Generated by Django 3.2.6 on 2021-09-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_delete_sessionspagetestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionspagesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session', verbose_name='sessie'),
        ),
    ]
