# Generated by Django 3.2.6 on 2021-09-25 18:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_sessionspagesession_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsPageTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.sessionspage')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.testimonial', verbose_name='getuigenis')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('page', 'testimonial')},
            },
        ),
    ]
