# Generated by Django 3.2.6 on 2021-09-25 18:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_delete_sessionspagesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsPageSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='home.sessionspage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session', verbose_name='sessie')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('page', 'session')},
            },
        ),
    ]
