# Generated by Django 3.2.6 on 2021-09-25 18:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0036_sessionspagesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionspage',
            name='info',
            field=models.CharField(blank=True, default='', max_length=264, verbose_name='info tekst'),
        ),
        migrations.AddField(
            model_name='sessionspage',
            name='subscribe_button',
            field=models.CharField(default='Schrijf je in', max_length=64, verbose_name='Button tekst'),
        ),
        migrations.AddField(
            model_name='sessionspage',
            name='subtitle',
            field=models.CharField(default='Info over sessies', max_length=64, verbose_name='ondertitel'),
        ),
        migrations.AddField(
            model_name='sessionspage',
            name='upcoming_sessions_title',
            field=models.CharField(default='Komende sessies', max_length=64, verbose_name='Komende sessies titel'),
        ),
        migrations.CreateModel(
            name='SessionsPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='afbeelding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.sessionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
