# Generated by Django 3.2.6 on 2021-09-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210925_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='subscription_link',
            field=models.URLField(blank=True, null=True, verbose_name='inschrijvingslink'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subscription_link_text',
            field=models.CharField(default='Schrijf je hier in', max_length=64, null=True, verbose_name='tekst voor link'),
        ),
    ]
