# Generated by Django 3.2.6 on 2021-09-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0038_auto_20210928_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='wat is DBS pagina'),
        ),
    ]
