# Generated by Django 3.2.6 on 2021-09-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0039_homepage_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='contact pagina'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='media_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='media pagina'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sessions_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='sessies pagina'),
        ),
    ]
