# Generated by Django 3.2.6 on 2021-09-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20210929_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.aboutpage', verbose_name='wat is DBS pagina'),
        ),
    ]
