# Generated by Django 3.2.6 on 2021-10-06 19:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0044_sessionspage_subtitle_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelivePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(default='info over DBS', max_length=64, verbose_name='ondertitel')),
                ('read_more', models.CharField(max_length=64, verbose_name='Lees meer')),
            ],
            options={
                'verbose_name': 'Relive page',
                'verbose_name_plural': 'Relive pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='video',
            name='relive',
            field=models.BooleanField(default=False, verbose_name='Is herbeleef video?'),
        ),
        migrations.CreateModel(
            name='RelivePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='afbeelding')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.relivepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='naam')),
                ('link', models.URLField(max_length=64, verbose_name='URL')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Pulicatie',
                'verbose_name_plural': 'Pulicaties',
            },
        ),
    ]
