# Generated by Django 3.2.6 on 2021-10-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0045_auto_20211006_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='relivepage',
            name='download_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Download bestand'),
        ),
        migrations.AddField(
            model_name='relivepage',
            name='download_text',
            field=models.CharField(default='Download de info brochure', max_length=64, verbose_name='Download tekst'),
        ),
    ]
