# Generated by Django 3.2.6 on 2021-10-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20211006_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publicatie', 'verbose_name_plural': 'Publicaties'},
        ),
        migrations.AddField(
            model_name='relivepage',
            name='info',
            field=models.CharField(default='Lorem ipsum', max_length=512, verbose_name='info tekst'),
        ),
        migrations.AddField(
            model_name='relivepage',
            name='subtitle_publication',
            field=models.CharField(default='Externe studies', max_length=64, verbose_name='publicaties titel'),
        ),
        migrations.AddField(
            model_name='relivepage',
            name='subtitle_relive',
            field=models.CharField(default='Herbeleef de DBS rondleiding', max_length=64, verbose_name='herbeleef titel'),
        ),
    ]
