# Generated by Django 3.2.6 on 2022-01-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_contactpageteammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date'], 'verbose_name': 'Sessie', 'verbose_name_plural': 'Sessies'},
        ),
        migrations.DeleteModel(
            name='SessionsPageSession',
        ),
    ]
