# Generated by Django 3.2.6 on 2022-01-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20220108_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionsPageTestimonial',
        ),
    ]
