# Generated by Django 3.2.6 on 2022-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_relivepage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relivepage',
            name='info',
            field=models.TextField(default='Lorem ipsum', verbose_name='info tekst'),
        ),
    ]
