# Generated by Django 3.2.6 on 2022-01-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_relivepage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionspage',
            name='info',
            field=models.TextField(blank=True, default='', verbose_name='info tekst'),
        ),
    ]
