# Generated by Django 3.2.6 on 2022-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_sessionspage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='link',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
