# Generated by Django 3.2.6 on 2022-01-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_session_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('NL', 'Nederlands'), ('FR', 'Francais'), ('DE', 'Deutsch')], default='EN', max_length=18, null=True),
        ),
    ]
