# Generated by Django 3.2.6 on 2022-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_session_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='info_text',
            field=models.TextField(default='', null=True, verbose_name='DBS info'),
        ),
    ]
