# Generated by Django 3.2.6 on 2022-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_homepagenew'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliveVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_nl', models.CharField(max_length=64, null=True)),
                ('title_fr', models.CharField(max_length=64, null=True)),
                ('link_en', models.URLField(null=True)),
                ('link_nl', models.URLField(null=True)),
                ('link_fr', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Relive video',
                'verbose_name_plural': 'Relive videos',
            },
        ),
    ]
