# Generated by Django 3.2.6 on 2022-06-03 10:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20220603_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaboutpage',
            name='info',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Info'),
        ),
    ]
