# Generated by Django 3.2.6 on 2022-06-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_newaboutpage_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='about_page',
            new_name='info_page',
        ),
    ]
