# Generated by Django 3.2.6 on 2022-07-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_homepage_about_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_page',
        ),
    ]
