# Generated by Django 3.2.6 on 2022-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_homepage_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='founding_partners',
            field=models.CharField(default='Founding partners', max_length=128),
        ),
        migrations.AddField(
            model_name='homepage',
            name='more_information',
            field=models.CharField(default='More information', max_length=128),
        ),
    ]
