# Generated by Django 3.2.6 on 2022-12-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_homepage_supporting_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content_de',
            field=models.CharField(default='', max_length=512, verbose_name='Getuigenis (DE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_fr',
            field=models.CharField(default='', max_length=512, verbose_name='Getuigenis (FR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_nl',
            field=models.CharField(default='', max_length=512, verbose_name='Getuigenis (NL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.CharField(max_length=512, verbose_name='Getuigenis (EN)'),
        ),
    ]
