# Generated by Django 3.2.6 on 2022-12-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0075_alter_menuitem_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='PDF bestand'),
        ),
        migrations.AlterField(
            model_name='press',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Externe link'),
        ),
    ]
