# Generated by Django 3.2.6 on 2022-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20221217_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaboutpage',
            name='mission',
            field=models.CharField(max_length=512, null=True, verbose_name='missie'),
        ),
        migrations.AddField(
            model_name='newaboutpage',
            name='vision',
            field=models.CharField(max_length=512, null=True, verbose_name='visie'),
        ),
    ]
